/***************************************************************************//**
* \file IMAGIMOB_MODEL_tflm_y_data_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the IMAGIMOB_MODEL model in float representation.
* Date: 2024-06-20 17:23:40.547169
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef IMAGIMOB_MODEL_TFLM_Y_DATA_FLOAT_H
#define IMAGIMOB_MODEL_TFLM_Y_DATA_FLOAT_H

#include <stdint.h>


extern const uint8_t IMAGIMOB_MODEL_y_data_bin[];
#define IMAGIMOB_MODEL_Y_DATA_BIN_LEN (800)

#endif // IMAGIMOB_MODEL_TFLM_Y_DATA_FLOAT_H

