/***************************************************************************//**
* \file IMAGIMOB_MODEL_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains IMAGIMOB_MODEL model data.
* Date: 2024-06-20 17:23:38.816038
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef IMAGIMOB_MODEL_TFLM_MODEL_FLOAT_H
#define IMAGIMOB_MODEL_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t IMAGIMOB_MODEL_model_bin[];
#else
extern uint8_t IMAGIMOB_MODEL_model_bin[];
#endif // CY_ML_MODEL_MEM
#define IMAGIMOB_MODEL_MODEL_BIN_LEN (156816u)
#define IMAGIMOB_MODEL_ARENA_SIZE (27229u)

#endif // IMAGIMOB_MODEL_TFLM_MODEL_FLOAT_H

